### ISSUE TITLE
Create calculator MVP

### ISSUE THREAD

**Issue by evgenpapyrin** [Kondramin/Calculator_WebApi#1]
Out solution has to have follow operations:

1. addition 
2. subtraction 
3. multiplication 
4. division

Web API Resource:
/calculator POST
Body:
{
  x,
  y,
  operator
}
Result:
{
 result
}

Definition of done:
1. WebAPI;
2. Unit tests;

**Comment by Kondramin** [comment]
I can't assign you to Reviewers in my pull request
